In [2]:
import numpy as np
arr=np.random.randint(1,100,size=(10,5)) #here row means sample and col means features
print(arr.shape)

(10, 5)


In [7]:
b=arr.reshape(5,10)
# print(b.ndim)
# print(b.shape)
print(b)

[[84 76 31 74 48 81 82 30 89 90]
 [45 55 14 57 86 97 73 67 71 11]
 [22 37 62 35 24 60  3 98 15 23]
 [55 49 99 94 53 86 40 12 45 85]
 [ 2 39 36 34 49 62 14 97 41  2]]


In [11]:
flatten=b.flatten()
print(flatten)
column_wise_flattening=np.ravel(b,order='C')
print(column_wise_flattening)
row_wise=np.ravel(b,order='F')
print(row_wise)

[84 76 31 74 48 81 82 30 89 90 45 55 14 57 86 97 73 67 71 11 22 37 62 35
 24 60  3 98 15 23 55 49 99 94 53 86 40 12 45 85  2 39 36 34 49 62 14 97
 41  2]
[84 76 31 74 48 81 82 30 89 90 45 55 14 57 86 97 73 67 71 11 22 37 62 35
 24 60  3 98 15 23 55 49 99 94 53 86 40 12 45 85  2 39 36 34 49 62 14 97
 41  2]
[84 45 22 55  2 76 55 37 49 39 31 14 62 99 36 74 57 35 94 34 48 86 24 53
 49 81 97 60 86 62 82 73  3 40 14 30 67 98 12 97 89 71 15 45 41 90 11 23
 85  2]


# Concatenation

In [12]:
a=np.random.randint(1,10,size=(2,3))
b=np.random.randint(20,30,size=(2,3))
print(a)
print(b)

[[1 8 9]
 [9 4 1]]
[[21 27 24]
 [24 27 29]]


In [ ]:
con_row=np.concatenate((a,b),axis=0) # 0 means row wise
# mane akta matrix er nise r akta matrix bosbe 
print(con_row)

[[ 1  8  9]
 [ 9  4  1]
 [21 27 24]
 [24 27 29]]


In [ ]:
con_col=np.concatenate((a,b),axis=1) # column wise concat
# mane akta matrix er shate r akta pasha pashi boshbe 
print(a)
print(b)
print(con_col)

# row wise concetanate korar shomoi column same thakbe
# col wise concat korar shomoi row ta same thakte hobe


[[1 8 9]
 [9 4 1]]
[[21 27 24]
 [24 27 29]]
[[ 1  8  9 21 27 24]
 [ 9  4  1 24 27 29]]


In [16]:
# transpose

mat = np.array([[10,20,30],
                [30,40,50]
               ])
transpose=mat.T
print(transpose)

[[10 30]
 [20 40]
 [30 50]]


In [20]:
# array split

a = np.random.randint(1 ,10 , size =(10,))
print(a)
spilitted_array=np.array_split(a,3)
print(spilitted_array)
# split -> equal division
# splitted_array = np.split(a,3)

[8 6 9 9 1 3 8 6 2 4]
[array([8, 6, 9, 9]), array([1, 3, 8]), array([6, 2, 4])]


## arithmetic operator and mathematical functions

In [25]:
x = np.array([ 10 , 8 , 30 , 100 ])
y = np.array([ 2 , 3 ,4  ,5 ])
add=np.add(x,y)
print(add)
sub=x-y
print(sub)
mul=x*y
print(mul)
div=x/y
print(div)
remainder=x%y
print(remainder)

[ 12  11  34 105]
[ 8  5 26 95]
[ 20  24 120 500]
[ 5.          2.66666667  7.5        20.        ]
[0 2 2 0]


In [29]:
# mathematical function
# trigonometry
# sin , cos , tan takes values in radian
sin_val=np.sin(x)
print(sin_val)
cos_val=np.cos(x)
print(cos_val)

degree_conversion=np.rad2deg(x)
print(degree_conversion)

radin_conversion=np.deg2rad(x)
print(radin_conversion)

[-0.54402111  0.98935825 -0.98803162 -0.50636564]
[-0.83907153 -0.14550003  0.15425145  0.86231887]
[ 572.95779513  458.3662361  1718.87338539 5729.57795131]
[0.17453293 0.13962634 0.52359878 1.74532925]


In [30]:
#log

x = np.array([ 10 , 8 , 16 , 100 ])
base_10_log_val = np.log10(x)
print(base_10_log_val)


two_diye_bhag = np.log2(x)
print(two_diye_bhag)

sqrt= np.sqrt(x)
print(sqrt)

[1.         0.90308999 1.20411998 2.        ]
[3.32192809 3.         4.         6.64385619]
[ 3.16227766  2.82842712  4.         10.        ]


In [31]:
# different
s = np.sum(x)
print(s)

#prefix sum
cumul =np.cumulative_sum(x)
print(cumul)

134
[ 10  18  34 134]


In [32]:
# comparison - >,< , >= ,<= , == , !=

x = np.array([ 10 , 8 , 16 , 100 ])
y = np.array([ 2 , 3 ,16  ,5 ])

greater_than = x>y

print(greater_than)

equal = x==y

print(equal)

# all () -> shob true kina
# any() -> jekono ekta true ase kina

print(np.all(greater_than))

print(np.any(equal))


[ True  True False  True]
[False False  True False]
False
True


# Sorting

In [34]:
#inplace
x = np.array([ 10 , 8 , 16 , 100 ])
z=x.copy()
print(z)
z.sort()
print(z)

[ 10   8  16 100]
[  8  10  16 100]


In [36]:
# Copy soring
print(x)
sort_arr=np.sort(x)
print(sort_arr)
print(x)

[ 10   8  16 100]
[  8  10  16 100]
[ 10   8  16 100]


In [37]:
# 2d array sorting
mat = np.array([[10,3,5],[8,4,9]])

# horizon axis = 1

hor_sort = np.sort(mat,axis=1)
print(hor_sort)

vert_sort = np.sort(mat,axis=0)
print(vert_sort)


[[ 3  5 10]
 [ 4  8  9]]
[[ 8  3  5]
 [10  4  9]]


# Searching

In [40]:
print(x)
# np.where( condition , x , y ) if true x , otherwise replace with y
index=np.where(x==8) # return index
print(index)

arr=np.where(x>8,x,0) # return array
print(arr)

[ 10   8  16 100]
(array([1]),)
[ 10   0  16 100]


In [43]:
print(mat)
index=np.where(mat>8) # return index
print(index)
arr=np.where(mat>8,mat,0)
print(arr)

[[10  3  5]
 [ 8  4  9]]
(array([0, 1]), array([0, 2]))
[[10  0  0]
 [ 0  0  9]]


In [46]:
x = np.array([ 10,100 , 8 , 16 , 100 ])
print(x)
max_indx=np.argmax(x)
print(max_indx)
min_idx=np.argmin(x)
print(min_idx)

[ 10 100   8  16 100]
1
2


## counting in ndarray


In [47]:
a = np.random.randint(1 ,100 , size =(100,))
print(a)

[10 24 66 28 30 19 82 46 48 18  8 60 34 67 11 22 83 92 68 83 88 24 90 91
  5 43 41 48 84 17 70 24 65  7  8 10 41 22 62 94  2 86 23 58 89 98 81 41
 62 95 74 38  8 74 79 54 49 73 69  4 74 39 32 51 45 44 88 21 66 14 44 76
 68 78 28 46 72 44 81 87 75 61 86 42 67 32 27 90 62 55 22 52 87 17 80 89
 96 83 70 15]


In [49]:
value_greater_60=np.count_nonzero(a>60)
print(value_greater_60)

47


In [50]:
unique_value,count=np.unique(a,return_counts=True)
print(unique_value,count)

[ 2  4  5  7  8 10 11 14 15 17 18 19 21 22 23 24 27 28 30 32 34 38 39 41
 42 43 44 45 46 48 49 51 52 54 55 58 60 61 62 65 66 67 68 69 70 72 73 74
 75 76 78 79 80 81 82 83 84 86 87 88 89 90 91 92 94 95 96 98] [1 1 1 1 3 2 1 1 1 2 1 1 1 3 1 3 1 2 1 2 1 1 1 3 1 1 3 1 2 2 1 1 1 1 1 1 1
 1 3 1 2 2 2 1 2 1 1 3 1 1 1 1 1 2 1 3 1 2 2 2 2 2 1 1 1 1 1 1]
