In [2]:
import numpy as np
arr=np.random.randint(1,100,size=(10,5)) #here row means sample and col means features
print(arr.shape)

(10, 5)


In [7]:
b=arr.reshape(5,10)
# print(b.ndim)
# print(b.shape)
print(b)

[[84 76 31 74 48 81 82 30 89 90]
 [45 55 14 57 86 97 73 67 71 11]
 [22 37 62 35 24 60  3 98 15 23]
 [55 49 99 94 53 86 40 12 45 85]
 [ 2 39 36 34 49 62 14 97 41  2]]


In [11]:
flatten=b.flatten()
print(flatten)
column_wise_flattening=np.ravel(b,order='C')
print(column_wise_flattening)
row_wise=np.ravel(b,order='F')
print(row_wise)

[84 76 31 74 48 81 82 30 89 90 45 55 14 57 86 97 73 67 71 11 22 37 62 35
 24 60  3 98 15 23 55 49 99 94 53 86 40 12 45 85  2 39 36 34 49 62 14 97
 41  2]
[84 76 31 74 48 81 82 30 89 90 45 55 14 57 86 97 73 67 71 11 22 37 62 35
 24 60  3 98 15 23 55 49 99 94 53 86 40 12 45 85  2 39 36 34 49 62 14 97
 41  2]
[84 45 22 55  2 76 55 37 49 39 31 14 62 99 36 74 57 35 94 34 48 86 24 53
 49 81 97 60 86 62 82 73  3 40 14 30 67 98 12 97 89 71 15 45 41 90 11 23
 85  2]


# Concatenation

In [12]:
a=np.random.randint(1,10,size=(2,3))
b=np.random.randint(20,30,size=(2,3))
print(a)
print(b)

[[1 8 9]
 [9 4 1]]
[[21 27 24]
 [24 27 29]]


In [ ]:
con_row=np.concatenate((a,b),axis=0) # 0 means row wise
# mane akta matrix er nise r akta matrix bosbe 
print(con_row)

[[ 1  8  9]
 [ 9  4  1]
 [21 27 24]
 [24 27 29]]


In [ ]:
con_col=np.concatenate((a,b),axis=1) # column wise concat
# mane akta matrix er shate r akta pasha pashi boshbe 
print(a)
print(b)
print(con_col)

# row wise concetanate korar shomoi column same thakbe
# col wise concat korar shomoi row ta same thakte hobe


[[1 8 9]
 [9 4 1]]
[[21 27 24]
 [24 27 29]]
[[ 1  8  9 21 27 24]
 [ 9  4  1 24 27 29]]


In [16]:
# transpose

mat = np.array([[10,20,30],
                [30,40,50]
               ])
transpose=mat.T
print(transpose)

[[10 30]
 [20 40]
 [30 50]]


In [19]:
# array split

a = np.random.randint(1 ,10 , size =(10,))
print(a)
spilitted_array=np.array_split(a,3)
print(spilitted_array)
# split -> equal division
splitted_array = np.split(a,3)

[8 5 8 4 9 7 7 3 7 4]
[array([8, 5, 8, 4]), array([9, 7, 7]), array([3, 7, 4])]


ValueError: array split does not result in an equal division