Ndarray

In [2]:
import numpy as np

#1d Array
arr1=np.array([1,2,3])

#2d Array
arr2=np.array([[1,2,3,4],[1,2,3,4]])

#3d Array
arr3 = np.array([
    #1st floor
    [ [1,2,3], # row1
      [4,5,6]  ], #row2

    #2nd floor

     [[1,2,3], # row1
      [4,5,6]  ], #row2


    #3rd floor
      [[1,2,3], # row1
      [4,5,6]  ] #row2


])

Array attributes

In [3]:
# Check dimension
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)
#data type
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)
#shape
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)
#size
print(arr1.size)
print(arr2.size)
print(arr3.size)

1
2
3
int64
int64
int64
(3,)
(2, 4)
(3, 2, 3)
3
8
18


# ndarry data type

In [5]:
arr = np.array([1,2,3],dtype=np.int16)

print(arr.dtype)

arr = np.array([1.5,2.4,3.2])
print(arr.dtype)

int16
float64


## ndarray creation from existing data ( BONUS )

In [18]:
# list
lst=[10,23,33,21,43,22,42]
arr=np.array(lst)
# print(arr)
# print(type(arr))
# print(arr.dtype)
mixed_lst=[10,True,"Hello"]
arr=np.array(mixed_lst)
# print(arr)
# print(type(arr))
# print(arr.dtype)

# Matrix
matrix=[[1,2,3],[4,5,6]]
arr=np.array(matrix)
print(arr)
print(arr.dtype)
print(type(arr))
print(arr.shape)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
int64
<class 'numpy.ndarray'>
(2, 3)
2


In [19]:
tpl = (10,20,30)

arr = np.array(tpl,dtype=np.int32)
print(arr.dtype)
arr = arr.astype(np.int16)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

int32
[10 20 30]
<class 'numpy.ndarray'>
int16
(3,)
1


In [20]:
#set

st = { 1, 2, 3 }

arr = np.array(list(st))
# print(arr.dtype)
arr = arr.astype(np.int16)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[1 2 3]
<class 'numpy.ndarray'>
int16
(3,)
1


In [23]:
dc = { 'a' : 10 , 'b' : 20 , 'c' :30 }

keys = dc.keys()
values = dc.values()
items = dc.items()
print(items)

dict_items([('a', 10), ('b', 20), ('c', 30)])


In [28]:
# keys to ndarray
arr=np.array(list(keys))
print(arr)
print(type(arr))
print(arr.shape)
print(arr.ndim)
print(arr.size)

['a' 'b' 'c']
<class 'numpy.ndarray'>
(3,)
1
3


In [32]:
# values to ndarray
arr=np.array(list(values))
print(arr)
print(arr.size)
print(arr.shape)
print(arr.ndim)
print(arr.dtype)

[10 20 30]
3
(3,)
1
int64


In [37]:
# items to ndarray
arr=np.array(list(items))
print(arr)
print(type(arr))
print(arr.shape)
print(arr.ndim)
print(arr.size)

[['a' '10']
 ['b' '20']
 ['c' '30']]
<class 'numpy.ndarray'>
(3, 2)
2
6


## Creating ndarray from scratch

In [41]:
# np.zeros
arr=np.zeros((2,3),dtype=np.int32)
print(arr)
print(type(arr))
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[0 0 0]
 [0 0 0]]
<class 'numpy.ndarray'>
(2, 3)
2
6


In [48]:
# np.ones
arr=np.ones((3,4,3),dtype=np.int32)
print(arr)
print(arr.shape)
print(type(arr))
print(arr.ndim)
print(arr.dtype)
print(arr.size)

[[[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]]
(3, 4, 3)
<class 'numpy.ndarray'>
3
int32
36


In [58]:
#np.empty= declare in memory but not initialize value.Later we can fill value
arr=np.empty((4,3),dtype=np.int32)
arr.fill(5)
print(arr)
print(arr.shape)
print(type(arr))
print(arr.ndim)
print(arr.dtype)
print(arr.size)

[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]
(4, 3)
<class 'numpy.ndarray'>
2
int32
12


In [62]:
# np.full
arr=np.full((4,3),np.inf)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]]
<class 'numpy.ndarray'>
float64
(4, 3)
2
12


# array creation with random values

In [ ]:
# np.random.rand(shape) range here greater 0 less 1
# Every time generate a random number
arr=np.random.rand(2,3)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[0.60194522 0.31458975 0.20711154]
 [0.175264   0.41608544 0.49901893]]
<class 'numpy.ndarray'>
float64
(2, 3)
2
6


In [ ]:
# np.random.randint(start,end, shape)
# Here everytime will generate a int number, we have to mention the starting, ending and shape of array
arr=np.random.randint(1,5,(2,3))
print(arr)

[[2 2 1]
 [1 2 2]]


In [74]:
# np.random.uniform(start,end, shape)

arr = np.random.uniform(50,100, (3,3,4))

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[[51.29834588 52.93070205 65.52490406 71.03288276]
  [53.69973433 76.50117518 76.55231917 53.53143904]
  [57.76708958 59.36230113 93.39198697 81.76644389]]

 [[98.46838826 99.639473   69.0075748  85.11689774]
  [64.21444475 93.52995708 88.79768816 50.66793366]
  [50.76334344 66.56924387 82.34861867 90.9304851 ]]

 [[78.76318569 82.50103293 77.08560226 73.98774575]
  [88.39376573 75.59529691 73.29657642 55.77318549]
  [81.88472548 80.40711702 51.58374934 53.31539044]]]
<class 'numpy.ndarray'>
float64
(3, 3, 4)
3
36


## array creation with range functions


In [77]:
# np.arange(first , end , step ) -> similar to range function
arr=np.arange(1,10,1)
mat=arr.reshape(3,3)
print(mat)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
int64
(9,)
1
9


In [78]:
# np.linspace(start , end(included) , koita)

arr = np.linspace(0, 4 ,6)


print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[0.  0.8 1.6 2.4 3.2 4. ]
<class 'numpy.ndarray'>
float64
(6,)
1
6


In [79]:
# np.logspace(start , end(included) , koita )

arr = np.logspace(0 , 4 ,6, base =2)

print(arr)

[ 1.          1.74110113  3.03143313  5.27803164  9.18958684 16.        ]


# Matrix


In [80]:
diagonal_matrix = np.diag([1,2,3,4])

print(diagonal_matrix)
print(diagonal_matrix.shape)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
(4, 4)


In [82]:
# identity matrix

identity_mat = np.eye(4)
print(identity_mat)
print(identity_mat.shape)


# np.eye(row , column,k)

# mat = np.eye(3,4)
# print(mat)

# mat = np.eye(3,4,1)
# print(mat)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
(4, 4)
