Ndarray

In [2]:
import numpy as np

#1d Array
arr1=np.array([1,2,3])

#2d Array
arr2=np.array([[1,2,3,4],[1,2,3,4]])

#3d Array
arr3 = np.array([
    #1st floor
    [ [1,2,3], # row1
      [4,5,6]  ], #row2

    #2nd floor

     [[1,2,3], # row1
      [4,5,6]  ], #row2


    #3rd floor
      [[1,2,3], # row1
      [4,5,6]  ] #row2


])

Array attributes

In [3]:
# Check dimension
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)
#data type
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)
#shape
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)
#size
print(arr1.size)
print(arr2.size)
print(arr3.size)

1
2
3
int64
int64
int64
(3,)
(2, 4)
(3, 2, 3)
3
8
18


# ndarry data type

In [5]:
arr = np.array([1,2,3],dtype=np.int16)

print(arr.dtype)

arr = np.array([1.5,2.4,3.2])
print(arr.dtype)

int16
float64


## ndarray creation from existing data ( BONUS )

In [18]:
# list
lst=[10,23,33,21,43,22,42]
arr=np.array(lst)
# print(arr)
# print(type(arr))
# print(arr.dtype)
mixed_lst=[10,True,"Hello"]
arr=np.array(mixed_lst)
# print(arr)
# print(type(arr))
# print(arr.dtype)

# Matrix
matrix=[[1,2,3],[4,5,6]]
arr=np.array(matrix)
print(arr)
print(arr.dtype)
print(type(arr))
print(arr.shape)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
int64
<class 'numpy.ndarray'>
(2, 3)
2


In [19]:
tpl = (10,20,30)

arr = np.array(tpl,dtype=np.int32)
print(arr.dtype)
arr = arr.astype(np.int16)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

int32
[10 20 30]
<class 'numpy.ndarray'>
int16
(3,)
1


In [20]:
#set

st = { 1, 2, 3 }

arr = np.array(list(st))
# print(arr.dtype)
arr = arr.astype(np.int16)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[1 2 3]
<class 'numpy.ndarray'>
int16
(3,)
1


In [23]:
dc = { 'a' : 10 , 'b' : 20 , 'c' :30 }

keys = dc.keys()
values = dc.values()
items = dc.items()
print(items)

dict_items([('a', 10), ('b', 20), ('c', 30)])


In [28]:
# keys to ndarray
arr=np.array(list(keys))
print(arr)
print(type(arr))
print(arr.shape)
print(arr.ndim)
print(arr.size)

['a' 'b' 'c']
<class 'numpy.ndarray'>
(3,)
1
3


In [32]:
# values to ndarray
arr=np.array(list(values))
print(arr)
print(arr.size)
print(arr.shape)
print(arr.ndim)
print(arr.dtype)

[10 20 30]
3
(3,)
1
int64


In [37]:
# items to ndarray
arr=np.array(list(items))
print(arr)
print(type(arr))
print(arr.shape)
print(arr.ndim)
print(arr.size)

[['a' '10']
 ['b' '20']
 ['c' '30']]
<class 'numpy.ndarray'>
(3, 2)
2
6


## Creating ndarray from scratch

In [41]:
# np.zeros
arr=np.zeros((2,3),dtype=np.int32)
print(arr)
print(type(arr))
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[0 0 0]
 [0 0 0]]
<class 'numpy.ndarray'>
(2, 3)
2
6


In [48]:
# np.ones
arr=np.ones((3,4,3),dtype=np.int32)
print(arr)
print(arr.shape)
print(type(arr))
print(arr.ndim)
print(arr.dtype)
print(arr.size)

[[[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]]
(3, 4, 3)
<class 'numpy.ndarray'>
3
int32
36
